declare module '@components'
declare module '@components/Button'
declare module '@components/Toggler'
declare module '@themes'
declare module '@themes/acme'
declare module '@styles/reset'
declare module '@hooks/useThemeMode'
declare module 'local-storage-fallback'
